### ISSUE TITLE
Is it possible to use one field as the href text for another link column (combining two fields)

### ISSUE THREAD

**Issue by simon-r-white** [bwanders/dokuwiki-strata#13]
Sorry, me again.

I have three data entries on three separate pages:
````
On Page test:links:a

<data TEST>
Date: 2015-01-01
Title: Initial meeting
</data>
````
````
On Page test:links:b

<data TEST>
Date: 2015-01-02
Title: Second meeting
</data>
````
````
On Page test:links:c

<data TEST>
Date: 2015-01-05
Title: Final meeting
</data>
````

I'd like a two column table with the `Date` and `Title`, like the following:
````
<table ?date ?title>
?item is a: TEST
?item Date: ?date
?item Title: ?title
</table>
````
However, this has no link to the page with the data entry on.

You can get a link as follows:
````
<table ?item ?date ?title>
?item is a: TEST
?item Date: ?date
?item Title: ?title
</table>
````

However, is it possible to have just the `Date` and `Title` column, with one of them as a href link to the page holding the data entry?

I've tried:
````
<table ?date [link] ?title>
?item is a: TEST
?item Date: ?date
?item Title: ?title
</table>
````

Which makes the `Date` column into links... but the href target is wrong.

So I'm trying to combine two fields into one column with a `link` type.

**Comment by bwanders** [comment]
First off, the `ref`, `page` and `link` types serve three subtly different purposes:
  - `ref` is for referencing other data blocks; this type is aware of `entry title` fields, and understands how to work with data fragments.
  - `page` is for creating wiki links to other pages on the wiki; this type links to a page, and will use normal dokuwiki link handling for internal links.
  - `link` is to have dokuwiki's magic link syntax handle it; this type is capable of 'linking' anything that dokuwiki sees as a link, so it will work with external http:// links, email addresses, en also with internal links.

What you want is something that I have run into as well, and have yet to find a satisfying solution. The only solution that comes close is to implement a display-only type `titleref` that uses its type hint to be given a field that is to be used as the href caption; but because of the niche use for this type, I have not added it to the plugin.

In the specialised case you present, there is another solution: use the `entry title` field instead of a separate `Title` field. You can either give the page a meaningful name in the title, which will automatically be picked up by the strata plugin:
```
====== Initial meeting =======
On Page test:links:a

<data TEST>
Date: 2015-01-01
</data>
```
Or you can explicitly set the entry title:
```
On Page test:links:a

<data TEST>
Date: 2015-01-01
entry title: Initial Meeting
</data>
```

In both cases the `entry title` field will be set to something nice. Together with the useheading setting, this will allow the normal `ref` type to use the entry title as the title of the link.

**Comment by simon-r-white** [comment]
Ok, I was thinking it might require using entry title... but was getting confused with the `ref` and `link` distinction.

I think I'll use the `entry title` as the the date of the meeting (it seems more logical to me to have the link be the date rather than the meeting name - personal opinion of course).

I'm using my own `datetime` type for the `Date` field (just extended the `date` type to include HH:MM)... so I will have double entry of the date (both in `entry title` and `Date`), but I can get the effect I want.

I'm finding it very handy to define data entries using the snippets-plugin (although I'm having issues with that plugin's auto-replacement feature).

I'm slowly getting towards what I want.
