### ISSUE TITLE
Enumerate options for text entries

### ISSUE THREAD

**Issue by iainhallam** [bwanders/dokuwiki-strata#26]
I'm making a database of singers in DokuWiki, and trying out the Strata plugin. Seems to be going well, but I'm missing having an enum type; is there a way of setting up lists that restrict entry to only those items, such as a list of voice parts "Soprano, Alto, Tenor, Bass" so that we don't get typos polluting our database? For that matter, one form of Boolean like "Yes, No", would be another candidate for this.

**Comment by bwanders** [comment]
There is currently no way to restrict any input. The philosophy behind Strata is that users are allowed to input whatever they want, and can come back later to fix things.

This does mean that you get some data pollution (as you nicely call it). This would be best fixed by having a UI that does suggestions. As we currently do not have that, there are three options to provide some kind of insight or restriction:
  - You could implement a custom data type that limits the number of options. In my opinion this is the least desirable solution.
  - I have seen people make a simple "Currently used values" query that can be consulted to see what values are currently already used. This way everyone can quickly see if something they want to use is available as a synonym
  - The cleanest solution I have seen in use is to make the restricted fields a `[ref]` type. That would mean that users get red-links if they use terms that do not link to an explanation page. For example, you could make pages for Soprano, Alto, etc. and then have a `Voice part [ref]` field that refers to them.

Hope that helps!
