### ISSUE TITLE
Limiting the number of rows to be displayed for table ui

### ISSUE THREAD

**Issue by jay9000** [bwanders/dokuwiki-strata#28]
I'm working on a database with more than 10.000 data entries. Is there an option to define how many rows should be displayed?  
I know that the Structured Data Plugin has the options `max` and `limit` and makes the table browsable if more rows are available. Some kind of pagination would be great to use the cool user interface with filters of strata for lots of data entries.

**Comment by bwanders** [comment]
Currently, there is no option to define how many rows should be displayed.

I agree that pagination would be nice, but since the filtering interface is complete client-side this would mean that pagination should also be client side -- and that means sending all 10k rows to the client when they browse to the page... I do not think that would be conductive to the user experience.

Unfortunately, I do not currently see a good way to combine pagination with our current filtering handling. Pull requests are welcome!
